version: '3.8'
services:
    backend:
        build: 
            dockerfile: ./Calories.Api/Dockerfile
            context: .
        ports:
            - 19999:80
        environment :
            calories_connectionstring: Server=10.144.179.91;User ID=calories;Password=calories;Database=calories
        depends_on:
            - frontend
        restart: always
    frontend:
        build: 
            dockerfile: ./Dockerfile
            context: ./Calories.Web/.
            args:
                REACT_APP_BACKEND_HOST: "localhost:10321"
        ports:
            - "9080:80"
        restart: always
