version: '3.8'
services:
    frontend:
        build: ./Calories.Web/.
        environment: 
            REACT_APP_BACKEND_HOST: "localhost:9999"
        ports:
            - "9080:9080"
    mysql:
        build: ./Calories.Database/.
        environment: 
            MYSQL_PASSWORD: "${db_password}"
        ports:
            - "3306:3306"
        volumes:
            - "mysql_data:/var/lib/mysql"
volumes:
    mysql_data: